### ISSUE TITLE
镜像 tag 与实际的  otel agent 版本不一致

### ISSUE THREAD

**Issue by Frapschen** [openinsight-proj/opentelemetry-java-instrumentation-extensions#17]
镜像版本是：ghcr.m.daocloud.io/openinsight-proj/autoinstrumentation-java:1.38.0-813ff1e42da4257b23f88deb1233ff7d59247f4b 但日志中却是 opentelemetry-javaagent - version: 1.32.0-SNAPSHOT

**Comment by JaredTan95** [comment]
fixed by https://github.com/openinsight-proj/opentelemetry-java-instrumentation-extensions/pull/23
